#pragma once

#define SERVER_IP	INADDR_ANY
#define SERVER_PORT 6000

#define MAX_USER 300
#define INVALID_ID ~0

#define BUF_SIZE 256
#define MAX_PACKET_SIZE 64
#define MAX_ROOM_NUM 100

#define FRAME_PER_SEC 50
#define FRAME_TIME (DWORD)(1000/FRAME_PER_SEC)